### ISSUE TITLE
大佬能帮帮我吗，把您的example下载下来后怎么使用

### ISSUE THREAD

**Issue by BaoZR** [mzhli/JNAeratorExample#1]
![图片](https://user-images.githubusercontent.com/53074211/86313960-fb734180-bc58-11ea-8234-449d850e6762.png)
点那个，要输什么命令（图片上传不了）

**Comment by BaoZhengRan** [comment]
![无标题](https://user-images.githubusercontent.com/53074211/86314046-3a08fc00-bc59-11ea-8235-f413bc7a90a8.png)
